# Generated by Django 2.2.2 on 2019-06-22 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramconfig',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paramconfig_set', related_query_name='paramconfig', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paramconfig',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='paramconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
